services:
  changedetection:
    image: ghcr.io/dgtlmoon/changedetection.io
    container_name: changedetection
    hostname: changedetection
    depends_on:
      playwright-chrome:
        condition: service_started
    volumes:
      - ./data:/datastore
      - ./proxies.json:/datastore/proxies.json
    environment:
      - PORT=5000
      - PUID=1000
      - PGID=1000
      # Log output levels: TRACE, DEBUG(default), INFO, SUCCESS, WARNING, ERROR, CRITICAL
      # - LOGGER_LEVEL=DEBUG

      # Alternative Playwright URL, do not use "'s or 's!
      - PLAYWRIGHT_DRIVER_URL=ws://playwright-chrome:3000

      # Playwright proxy settings playwright_proxy_server, playwright_proxy_bypass, playwright_proxy_username, playwright_proxy_password
            # https://playwright.dev/python/docs/api/class-browsertype#browser-type-launch-option-proxy

      # Base URL of your changedetection.io install (Added to the notification alert)
      - BASE_URL=https://${SERVICE_NAME}.${MY_DOMAIN}
      # Respect proxy_pass type settings, `proxy_set_header Host "localhost";` and `proxy_set_header X-Forwarded-Prefix /app;`
      # More here https://github.com/dgtlmoon/changedetection.io/wiki/Running-changedetection.io-behind-a-reverse-proxy-sub-directory
      - USE_X_SETTINGS=1
      - HIDE_REFERER=true
      - FETCH_WORKERS=10
      # Absolute minimum seconds to recheck, overrides any watch minimum, change to 0 to disable
      # - MINIMUM_SECONDS_RECHECK_TIME=3
    # ports:
      # - 5000:5000
    restart: unless-stopped
    networks:
      changedetection:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SERVICE_NAME}.entrypoints=http"
      - "traefik.http.routers.${SERVICE_NAME}.rule=Host(`${SERVICE_NAME}.${MY_DOMAIN}`)"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=default-whitelist@file"
      - "traefik.http.middlewares.${SERVICE_NAME}-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${SERVICE_NAME}.middlewares=${SERVICE_NAME}-https-redirect"
      - "traefik.http.routers.${SERVICE_NAME}-secure.entrypoints=https"
      - "traefik.http.routers.${SERVICE_NAME}-secure.rule=Host(`${SERVICE_NAME}.${MY_DOMAIN}`)"
      - "traefik.http.routers.${SERVICE_NAME}-secure.tls=true"
      - "traefik.http.routers.${SERVICE_NAME}-secure.service=${SERVICE_NAME}"
      - "traefik.http.services.${SERVICE_NAME}.loadbalancer.server.port=${SERVICE_INTERNAL_PORT}"
      - "traefik.docker.network=proxy"

  playwright-chrome:
    hostname: playwright-chrome
    image: dgtlmoon/sockpuppetbrowser:latest
    # cap_add:
    #   - SYS_ADMIN
    restart: unless-stopped
    environment:
      - SCREEN_WIDTH=1920
      - SCREEN_HEIGHT=1024
      - SCREEN_DEPTH=16
      - MAX_CONCURRENT_CHROME_PROCESSES=10
    networks:
      changedetection:

networks:
  changedetection:
  proxy:
    external: true
